### ISSUE TITLE
[Enhancement] need  modifying dockerfile for lint test

### ISSUE THREAD

**Issue by ebang091** [42Seoul-LastDance/Backend#14]
## 요약

- npm run lint 로 github action 에서 코드 컨벤션 및 문법 확인

<br><br>

## 내용

node.js 버전을 명시하는 부분이 있는데 dockerFile 의 image:node:latest 부분과 버전이 다를 수 있어,
dockerfile의 버전 명시가 필요해 보입니다. 
<img width="410" alt="스크린샷 2023-09-05 오후 11 47 37" src="https://github.com/42Seoul-LastDance/Backend/assets/108053947/b7564043-5592-4b1f-ac8f-161a8bd690a1">

<br><br>

## 참고자료

<br><br>

**Comment by Tolerblanc** [comment]
오오옹ㅇㅇ오

**Comment by Tolerblanc** [comment]
<img width="286" alt="image" src="https://github.com/42Seoul-LastDance/Backend/assets/52883827/2d70c06d-24f6-4e9c-a00e-ef1fab37457e">
<img width="623" alt="image" src="https://github.com/42Seoul-LastDance/Backend/assets/52883827/639ade42-a200-457d-8b1d-71a713e9d5f7">

[https://nodejs.org/ko/download/releases](https://nodejs.org/ko/download/releases)

그냥 20버전으로 명시해서 사용하여도 큰 문제는 없어보이긴 합니다!

**Comment by Tolerblanc** [comment]
오 Actions 짜두신거 보니까, `npm test` 동작하도록 테스트 코드만 짜두면 PR 날릴 때 테스트도 돌려볼 수 있겠는데요?

+++ `package.json`에 있는 친구들인데, 얘네도 Actions에서 바로 가져다가 쓸 수 있나봅니다
<img width="1047" alt="image" src="https://github.com/42Seoul-LastDance/Backend/assets/52883827/c3b7837e-9453-44ff-a22d-147add6a8dd1">

**Comment by ebang091** [comment]
@Tolerblanc 좋습니다! 그럼 가장 stable 한 버전은 현재 18인것 같으니. 18로 통일할까요?
그리고 test 돌릴 수 있는 것 맞아요! 테스트 문 몇개 적어두고 추가해둔 뒤 action 에도 추가하는 것 매우 좋아보입니다 ㅎㅎ

**Comment by Tolerblanc** [comment]
@ebang091 18버전으로 가시죠!!
