### ISSUE TITLE
환경변수(.env) 분리

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-LastDance/Backend#17]
## 내용

- 현재 전역 환경변수 파일(`/.env`) 과 nest 컨테이너용 환경변수 파일 (`/srcs/nest/.env`) 로 나뉘어 있는데, 관리의 용이함을 위해 합치는게 좋아보입니다.
- 전역 환경변수 파일만 두고, docker-compose를 통해 컨테이너에 주입한 다음
- `process.env.{key}`로 가져와서 쓰는게 가장 좋을듯 해용. 다른 의견 환영

<br>

**Comment by ebang091** [comment]
오 안그래도 그렇게 하기로 생각했었습니다! 다만 현재는 필요한 환경변수 내용도 정해져 있지 않아서 당분간은 로컬로 env 를 주고받고, 마지막에 고치면 되지 않을까 했었습니다!
어느쪽이든 더 편한 방향으로 하면 좋을 것 같습니다 ㅎㅎ

**Comment by OZestina** [comment]
process.env.{key}로 사용할 수 있었군요! 테스트해보고 잘 돌아가면 수정하면 좋겠어요 :D

**Comment by Tolerblanc** [comment]
#18 을 통해 해결되었고, .env 파일은 정리 후 로컬에서 관리하기로 하였으니 이슈 닫겠습니다!
