### ISSUE TITLE
[Feature] Socket : ChatRoom & DM

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-LastDance/Backend#23]
## 요약

- 현재까지의 구현과 추후 작업 내용을 정리하기 위한 이슈 

<br><br>

## 내용

- 현재까지의 구현
  - // ! Test 로 주석 처리된 부분 제외, 노션에 적힌 모든 게이트웨이 구현 완료
  - 다만, 직접 연결 후 테스트가 진행된 것이 아니라서 수정이 필요할 수 있음
- 예정 사항
  - ~노션 누락된 부분 체크하여 업데이트~
  - ~더미 토큰으로 테스트할 수 있도록 DB우회 로직 추가 ( -> 추가 게이트웨이를 파는 식으로 할까 고민중입니다.)~
    -> DB에 더미 데이터 넣는 방식으로 수정했습니다. (아래 커멘트 참조)
  - DM 로직에 친구 요청 게이트웨이 및 서비스 추가 ( -> 이 부분도 추가 협의가 필요할 것 같습니다.)
<br><br>

## 참고자료

- 노션 Socket.io 페이지
<br><br>

**Comment by Tolerblanc** [comment]
[09/28](https://github.com/42Seoul-LastDance/Backend/commit/091e8b4bf2627f970d52d882cd8697e6f6312062)
더미 데이터 삽입 후 jwt 발급하여 Postman으로 기본적인 연결 테스트 완료
- 더미 데이터 삽입
```bash
docker exec -it postgresql psql
\c pong_db
INSERT INTO "user" (id, username, email, "slackId") VALUES ('4242', 'testman', 'testman@42seoul.kr', 'testman');
select * from "user";
``` 
   - 더미 데이터의 JWT
```text
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjQyIiwibmFtZSI6InRlc3RtYW4iLCJpYXQiOjE1MTYyMjM0MjM0fQ.jZsy7aTM-GcoSbQW6TERNuTCBCvIS-7l_qfm5PMg0-U
```
  - Postman -> New -> Socket.io -> Headers에 "token" : JWT 추가 후 연결 시도
  - Events 에 Listen할 이벤트 추가 후 테스트

**Comment by JaeJunday** [comment]
> [09/28](https://github.com/42Seoul-LastDance/Backend/commit/091e8b4bf2627f970d52d882cd8697e6f6312062) 더미 데이터 삽입 후 jwt 발급하여 Postman으로 기본적인 연결 테스트 완료
> 
> * 더미 데이터 삽입
> 
> ```shell
> docker-compose exec -it postgresql psql
> \c pong_db
> insert into "user" (id, username, email, slackId) values ('4242', 'hyunjuki', 'hyunjuki@student.42seoul.kr', 'hyunjuki');
> select * from "user";
> ```
> 
> * 더미 데이터의 JWT
> 
> ```
> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjQyIiwibmFtZSI6Imh5dW5qdWtpIiwiaWF0IjoxNTE2MjIzNDIzNH0.UPVv3vDiROAVbRequxbMLnS9NXcR4QcfKGxY20kg-Qs
> ```
> 
> * Postman -> New -> Socket.io -> Headers에 "token" : JWT 추가 후 연결 시도
> * Events 에 Listen할 이벤트 추가 후 테스트
aaa

**Comment by Tolerblanc** [comment]
- **TODO**
- [x] 노션 업데이트 (9/28 16:00 기준)
- [ ] `ChatRoom.service.ts` TODO 주석 해결
- [ ] 프론트 / 백 변수명(lowercase, camelcase 통일)
- [ ] `kickUser` 로직 점검 : 타겟 유효성 검사가 완벽하지 않은 것 같음 + pastRoomName을 찾지 못하는 문제를 보아하니, 전체적으로 방 관리 로직이 정상 동작을 안하는 것 같음
- [ ] `muteUser` 테스트 필요 : 현재 `setTimeout()`으로 `MuteList` 갱신 중
- [x] `sendMessage`가 `userName`을 인자로 받고 있음 -> userId로 수정?
- [ ] 프론트 연결 후 전체적인 로직 테스트
- [x] DM 내역 가져오는 RestAPI 구현
- [ ] 친구 요청 및 추가 / 제거 구현, 게임 초대 및 privateChatRoom 초대 구현

**Comment by Tolerblanc** [comment]
- **Known Bugs**
- [ ] 새로고침 시 방 MemberList에 계속 같은 유저가 추가되는 현상 -> `defaultRoom`에는 멤버 삭제 로직이 없어서, 여기서만 일어나는 버그인듯
- [x] socketList{socketId-UserId} 에서, 특정 유저가 새로고침을 하면 `다른 소켓 아이디 - 같은 유저 아이디` 가 계속 추가되는 현상
    -> react의 dev 모드 렌더링 문제였음
- [x] pastRoomName을 찾지 못하는 문제

**Comment by Tolerblanc** [comment]
- 더미 데이터 하나 더 추가
```bash
docker exec -it postgresql psql
\c pong_db
INSERT INTO "user" (id, username, email, "slackId") VALUES ('4243', 'testman2', 'testman2@42seoul.kr', 'testman2');
select * from "user";
``` 
```text
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjQzIiwibmFtZSI6InRlc3RtYW4yIiwiaWF0IjoxNTE2MjIzNDIzNH0.RNiS0FrQ2nRBDSG0oBU-4AU4twkrN5p8StLhdCL4_wM
```

**Comment by Tolerblanc** [comment]
#### **Discussion**
- ~~`getChatRoomList` : DTO를 전부 담은 리스트를 넘기는게 아니라, 채팅방 이름만(또는 잠금 여부까지) 담겨있는 리스트를 반환. DTO를 넘기는 로직은 개별 방의 자세한 정보를 주는 게이트웨이로 분리 / 또는 개별 방의 자세한 정보(DTO 하나)를 주는 게이트웨이 추가
    -> `getChatRoomDto`?~~ `getChatRoomInfo`로 분리 완료!
- `default room` : 실제 구현에서도 광장 느낌으로 유지 시킬 것인지? -> maybe not? dm을 전역 소켓으로 쓰니까
- ~~방폭파 로직 : owner가 나가는 순간 방 자체를 폭파시킬 것인지?~~ -> owner 나가면 폭파되도록 수정 완료
- ~~`roomName` : 채팅방 이름은 항상 유니크하게?~~ -> 수정사항으로
[] create 전에 검사하도록 수정 
- `block` : 유저가 다른 유저를 블락할 때의 처리?  -> 백엔드가 socket별로 확인? -> 프론트랑 대화
    > Subject :  The user should be able to block other users. This way, they will see no more
messages from the account they blocked.
- `blockList` : 리스트 관리를 ( 프론트 + DB / 백 인메모리 ) 어떻게 관리하여 처리할 것인지? -> DB로 저장하고 조회하는 식 제안드립니다
- public 채팅방에 속해 있는 유저 리스트를 전부 보여주면, 친구가 아니어도 Status를 알 수 있게됨 -> default room 사용 성 여부/ 가시성 여부 정하기

**Comment by ebang091** [comment]
- status 검사 (getStatus : default room 에서 접속 중인지 확인? 
- default room 가시성 여부(status 확인, private room 초대 용으로 내부적으로만 가지고 있을까요?  - 미정)
- [ ] memberList에서 chatRoom 멤버가 제대로 지워지지 않는 문제

**Comment by JaeJunday** [comment]
* 프론트에서 유저 id를 가지고 있지 않는 식으로 변경한 이유로 ChatRoomDto의 memberList[]가 id가 아닌 닉네임 배열이 필요합니다.

**Comment by Tolerblanc** [comment]
@JaeJunday 
> * 프론트에서 유저 id를 가지고 있지 않는 식으로 변경한 이유로 ChatRoomDto의 memberList[]가 id가 아닌 닉네임 배열이 필요합니다.


수정은 어렵지 않은데, ChatRoomDto를 요청시 마다 DB를 찌르는 방향으로 구현해야 할 것 같습니다.
그러면 닉네임 변경에 대한 실시간 감지가 어려울 것 같은데, 이거는 어떻게 할까요??

**Comment by ebang091** [comment]
@Tolerblanc @JaeJunday 
닉네임 변경 시에는 chatroom 을 반드시 나갔다가 들어와야 하는 과정이 포함되니, 문제가 없을 수도 있지 않을까요? chat 영역을 벗어났을 때 소켓이 disconnect 되는게 확실하다면, 문제 삼지 않아도 된다고 제안드려봅니다! 혹시 다른 발생가능한 문제가 있을까요?

**Comment by Tolerblanc** [comment]
@ebang091 오! 그걸 생각 못했네요. 서버에서 join 이벤트를 처리할 때 memberList 이벤트를 브로드캐스트 해주고, 클라이언트에서 해당 이벤트를 받을 때마다 리스트 갱신을 시켜주면 깔끔할 것 같습니다!!

**Comment by ebang091** [comment]
@Tolerblanc @JaeJunday 
너무 좋습니다~~~ 
프론트 id - username 테이블 구조를 가지지 않은 구조로 설계했다는 것도 이해했습니다!!
+ 현준님의 의견은 다른 client에게 새로운 유저가 방에 들어왔다는 것을 알리는 방법으로 'memberList' 라는 이벤트에서 새로운 유저 정보(username)을 전달해야한다는 뜻이시지요? (memberList 이벤트: roomname, new username 전달)

+ 그리고 ChatRoomInfo 이벤트 요청을 받았을 때는 memberList 를 전달할 때 저희가 가진 id리스트를 가지고 username 리스트를 만드는 방식 생각중이신거죠?

**Comment by Tolerblanc** [comment]
@ebang091 
1. 앗 정정하겠습니다! 새 유저가 방에 들어온 것과 상관없이, 클라이언트가 서버로부터 `memberList` 이벤트를 수신할 때 현재 채팅방의 유저 리스트를 다시 그립니다. 서버는 현재 채팅방의 `Array<string> username`만 보내주는 방식이에요. 유저가 나갈때에도(또는 강퇴 당할때에도) 유저 리스트를 갱신해줘야 하니까, 이렇게 빼두면 요긴할 것 같아요.
서버에서 보내주는 정보를 조금 더 수정하면, 오퍼레이터가 새로 생기거나 없어지는 경우, 누군가 뮤트되는 경우 등 특정 유저의 상태가 변할 때마다 똑같은 `memberList` 이벤트만 던져주면 되겠군요!

2. 네 맞아요!! 쿼리문 한 줄로 바로 만들어 줄 수 있을 것 같습니다. 

++ 1번과 같은 구현 방식을 채택한다면, ChatRoomDto를 전부 보내줄 필요도 없을 것 같습니다. RoomInfoDto만 보내서 현재 채팅방에 대한 간단한 정보만 그리도록 하고, 실시간으로 갱신되어야 하는 유저 리스트는 갱신될 때마다 서버에서 `memberList` 이벤트를 보내주는 게 더 옳은 방향이라는 생각이 들어요.

**Comment by ebang091** [comment]
@Tolerblanc 저도 동의합니다! 그 방향으로 진행해보겠습니다!~

**Comment by Tolerblanc** [comment]
1. 소켓 연결 시 프론트로부터 jwt만 넘겨 받고, 백에서 복호화하여 처리
2. blockList는 DB로 관리하고, 관련 이벤트 발생 시 백에서 for문 돌면서 처리
3. 특정 채팅방의 유저 정보가 변경될 때마다 getChatRoomInfo 이벤트 발생
4. 백에서는 userId-Socket, socketId-userId 맵 두개로 유저-소켓 정보 관리중. 프론트 단으로 userId를 직접 넘기는 일은 없으며, 넘어가는 유저관련 정보들은 모두 DB를 찍어서 userName으로 바꿔서 전달
5. `getChatRoomInfo` 이벤트의 리턴 = `ChatRoomDto`의 모든 정보들 + `myName:string` + `myPermission: UserPermission`
