### ISSUE TITLE
[Bug] Game part Backend

### ISSUE THREAD

**Issue by SikPang** [42Seoul-LastDance/Backend#24]
## 버그 리포트

> 버그에 대해 알려주세요
### 1. gameOver 시 DB 저장 에러 추정됩니다
```
nest          | Error: game => internal error while save DB
nest          | 
nest          | /usr/app/srcs/src/game/game.service.ts:424
nest          |             throw new InternalServerErrorException(
nest          |                   ^
nest          | InternalServerErrorException: error while save game data
nest          |     at GameService.createGameData (/usr/app/srcs/src/game/game.service.ts:424:19)
nest          |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
nest          |     at GameService.finishGame (/usr/app/srcs/src/game/game.service.ts:358:9)
nest          |     at GameService.handleDisconnect (/usr/app/srcs/src/game/game.service.ts:100:17)
nest          |     at GameGateway.handleDisconnect (/usr/app/srcs/src/game/game.gateway.ts:31:9)
```
<br>

### 2. gameOver 시 오는 data 불일치
```
{
leftScore: 0
reason:1
rightScore: 5
winner:1
}
```
테스트 시점에 rightScore가 5가 아니었습니다. (혹시 cheating이라 최고점 줘버린 것..?)
<br>

### 3. movePaddle 이벤트 시 상대한테 안 주고 이벤트 보낸 사람한테 보내는 듯합니다
```
const side = this.playerList.get(playerId).side;
const rival = this.gameRoomList.get(roomId).socket[side]; // <--- (side + 1) % 2로 바꾸니 해결되네요
```
<br>

### 4. movePaddle 이벤트 변수명 앞글자 소문자로 바꿔주세요
  `PaddlePosX `-> `paddlePosX`
<br><br>

### 5. 실수 비교 보완해 주세요! 약 0.1정도?
  예) `0.7499482 == 0.75`
<br><br>

### 6. ballHit로 점수 내고 난 이후 startGame 이벤트 오지 않아요
 이것도 실수 비교 문제네요
<br><br>

### 7. 처음 startGame 이벤트 시 ballDir 값이 크게 설정되는 부분
-> 지금 서버에서 주는 ballDir를 정규화시켜서 진행하고 있는데 이 부분이 validCheck에서 안 좋게 작용할 수도 상관 없을 수도 있습니다 확인 필요
<br><br>

### 8. ballHit로 정상 종료시 gameOver Event 오지 않아요
<br><br>

### 9. sendEmoji 보낸 데이터는 잘 콘솔에 출력되는데 오는 데이터는 null이에요 
코드 확인해보니까 nest 쪽에서 데이터는 string인 것 같은데 뭔지 모르겠네요
<br><br>

**Comment by OZestina** [comment]
해당 이슈관련 코드 업데이트해 push 완료했습니다
