### ISSUE TITLE
[Enhancement] Game part 보완점

### ISSUE THREAD

**Issue by SikPang** [42Seoul-LastDance/Backend#25]
### 1. startGame 이벤트 주실 때 leftScore, rightScore 같이 주셔야할 것 같아요
인게임에서 공이 양 옆 충돌 처리에 의존해서 점수가 올라가는데, ballHIt으로 guest에게 줘서 ball 위치를 바꿔버리는 바람에 ball의 충돌 처리에 의존하기가 힘들어졌어요

<br/><br/>

### 2. startGame 이벤트 주실 때 공 스피드도 주시면 좋을 것 같아요
공 스피드를 '난이도별로' 저장하고 있다가 주시면 좋을 듯 해요
validCheck도 난이도별로 다르게 체크.. 되어있을까요? 되어있음 말구

**Comment by OZestina** [comment]
해당 이슈 대응해 업데이트했고, push완료했습니다~
