### ISSUE TITLE
[Feature] chat Room block list

### ISSUE THREAD

**Issue by ebang091** [42Seoul-LastDance/Backend#26]
## 요약
blockList 를 백에서 관리 시 유저 별로 차단한 메시지를 띄우기가 불가합니다.

<br><br>

## 내용

front 에서 sendMessage 이벤트 보내면 back이 blockList 를 순회하면서 특정 유저는 제외하고 메시지를 보내려고 했는데, 
blockList 자제가 send 한 사람의 차단 리스트일 뿐 유저 각각의 blocklist 에 맞춘 것이 아닌 문제가 있습니다. 
해결책으로는  프론트가 렌더링 전에 한번 더 event 를 요청해서 보낼지 말지 허가를 받고(CanSendMessage 수신 하면) 렌더링하는 방법이 있을 것 같습니다. 
(렌더링 전에 조건문 검사는 blockList 순회까지 해야하니  프론트가 할 일이 많아지니 제안하지 않았습니다~) 
<br><br>

## 참고자료

<br><br>

**Comment by Tolerblanc** [comment]
유저 A 가 B를 차단한 상태에서 클라이언트에 메시지를 적은 후 전송 버튼을 누를 때 `sendMessage` 이벤트가 발생할텐데,
이 경우 A->B 메시지는 서버단에서 막을 수 있지만(사실 얘는 안막는게 맞겠네요)
 B->A 메시지는 막을 수 없다는 부분을 짚어주신 게 맞을까요??
 
  >jaejkim> A->B를 막는 순간 채팅쳤는데 화면에 안그려진다거나... 채팅방에 한명이라도 날 차단한 사람이 있다면 채팅이 안쳐지겠네요


맞다면 구현하기 조금 빡세겠지만, `blockList` 와 `blockedByList`(누구에게 차단 당했나 목록) 두 개를 운용하는 방법도 있을 것 같습니다.
_send_ 와 _receive_ 이벤트를 분리해서, _receive_ 이벤트를 받은 소켓의 `blockedByList`를 순회해서 걸러내면 어찌저찌 될 것 같기도 하네용

**Comment by JaeJunday** [comment]
프론트에서 메세지를 받았을때 `send('userName', 'message')`이 상태일 텐데, 받아서 바로 화면에 렌더링 하지 않고 
받은 쪽에서 다시 `recv('myName', 'userName')`를 보내고 응답으로 성공 or 실패로 렌더링 해준다면 백쪽 로직이 좀 깔끔해지지 않을까요? 

blocklist와 blockedbyList를 분리할 필요는 없어보입니다. 
왜냐하면 프론트에서 보낸 myName과 userName간에 서로 blocklist에만 없으면 화면에 띄우면 되니까요.

**Comment by Tolerblanc** [comment]
>해결책으로는 프론트가 렌더링 전에 한번 더 event 를 요청해서 보낼지 말지 허가를 받고(CanSendMessage 수신 하면) 렌더링하는 방법이 있을 것 같습니다.

>받은 쪽에서 다시 recv('myName', 'userName')를 보내고 응답으로 성공 or 실패
  프론트에서 보낸 myName과 userName간에 서로 blocklist에만 없으면 화면에 띄우면 되니까요.

와... 이렇게 구현하면 되겠군요

메시지 하나 당 DB 접근이 (받는 유저 수 - 1) 만큼 일어날 텐데, 최적화 여부는 일단 구현한 뒤에 생각해보면 좋을 것 같습니다.

**Comment by JaeJunday** [comment]
만약 서버의 메모리 공간에 소켓의 런타임동안 유저별로 차단 유저목록을 들고 있을 수 있는 여력이 있다면 그냥 객체 형태로 데이터를 들고 있다가 소켓이 disconnect 될때만 해당 소켓의 block list에 대한 DB update를 진행할 수도 있을것 같습니다.
> 의미없는 성능걱정인것 같습니다. 동시접속자수를 얼마나 늘려야 부하가 생기는지 특정할수 없는 시점에서 고려해서 로직을 짠다는게 불가능합니다
> 캐싱으로 해결(한번 조회한 유저의 블락 리스트는 적어도 소켓이 끊기기 전까진 다시 조회하지 않음)

**Comment by Tolerblanc** [comment]
동의합니다. DM때 고민했던 거랑 비슷하게 결국 Redis를 도입하지 않는 이상, 의미없는 이야기인 것 같네요.

**Comment by Tolerblanc** [comment]
백에서 chatroom 관련 소켓 기능은 구현 완료하여 일단 이슈를 닫고, 추가 구현 및 버그 수정은 QA List 이슈에서 관리하겠습니다!

**Comment by ebang091** [comment]
ㄴ> 별도로 DM, Chat socket에서 사용할 수 있는 socketUserService를 구현하면서, 싱크는 맞추고 DB접근은 덜하는 방법으로 구현했습니다! 인터페이스가 하나 생긴느낌이라 훨씬 보기도 깔끔하고 관리도 편한 것 같아요
