### ISSUE TITLE
socket 연결과 jwt 토큰 

### ISSUE THREAD

**Issue by ebang091** [42Seoul-LastDance/Backend#27]
## 요약

프론트에 socket이 토큰 만료로 연결 실패하면 재발급 요청 로직 있어야 할 것 같습니다.
(regenerateJwt 이벤트 만들어서 back에서 받고 저장하는 걸로 제안드립니다!)
<br><br>

## 내용

- regenerate Jwt 이벤트를 통해서 (refreshtoken)을 저희에게 보내주시면 저희가 refresh token을 DB 에서 검증 후 jwt 토큰을 새로 발급해드리는 로직입니다. 

- 다른 방법으로는 소켓 연결마다 매번 재발급해서 드릴 수는 있는데 그렇게 되면 소켓 연결될 때마다 새롭게 jwt 저장해야하는 로직으로 갈 것 같아요. 
- 그렇다 해도 refreshToken 만료됐을 때는 로그인 다시 유도해야하는 로직은 원래도 필요할 것 같아요!

다시 요약: 
- jwt 만료 시 재발급 로직은 1)백에서 매번 해줘도 되고 2()프론트에서 소켓 연결 fail 확인하고 back 으로 재발급 요청해줘도 된다.
- refreshtoken(jwt가 아니라 refreshtoken 도 만료되면 사용자 정보 자체가 다 만료라고 보면 됩니다) 이 만료되면 다시 로그인하도록 유도하는 것은 아무튼 필요해보입니다..! 

<br><br>

## 참고자료

<br><br>

**Comment by Tolerblanc** [comment]
1. `handleConnection` 시에 Jwt 검사를 해보고, 만료된 토큰을 받았을 경우 특정 이벤트를 보냄
2. 특정 이벤트를 프론트에서 받으면 백으로 refreshToken을 통한 재발급 요청을 보냄
3. 재발급 요청이 유효하다면 새로운 accessToken 세팅, 실패한다면 로그인 페이지로 리다이렉션
요렇게 될까요??

**Comment by JaeJunday** [comment]
프론트 소켓이슈 해결해서 백쪽 handshake같이 이상한 이벤트 만들었던거 다시 없앴습니다. 
jwt 세팅 query -> auth 로 수정했습니다. 
refresh token 재발급하는 api가 404를 던지는 이슈가 있는데 체크해보겠습니다...
소켓 연결을 끊지 않고 옵션만 바꿀수있는 걸 찾아보고 있었는데 불가능해 보입니다.

**Comment by SikPang** [comment]
해결했습니다!
