### ISSUE TITLE
[Feature] 친구 status 실시간 업데이트 방식

### ISSUE THREAD

**Issue by ebang091** [42Seoul-LastDance/Backend#28]
## 요약

- 가장 좋은 건 socket.io이벤트를 받아서 실시간으로 업데이트 해주는 것이지만, 우선 restapi 요청으로 새로고침 할 수 있게 만들면 좋을 것 같습니다. 
-

<br><br>

## 내용

restapi - friends/getFriendList 에서 {friendName, friendStatus}[] list를 반환받을 수 있습니다!
<br><br>

## 참고자료

<br><br>

**Comment by Tolerblanc** [comment]
@SikPang @JaeJunday 
친구들의 Status도 채팅방 목록처럼 실시간으로 업데이트 시켜주려면, 상태가 변할 때마다 이벤트를 발생시켜서 통신하도록 구현해야 할 것 같습니다. 혹시 구현하실 생각 있으시면 관련하여 어떻게 처리할 지 같이 이야기 해보면 좋을 것 같아요. 다른 namespace끼리 이벤트를 주고 받을 수 있는지 실험을 안해봐서, 어떻게 동작할 지는 모르겠습니다.
친구 목록에 새로고침 버튼을 달고, 그때마다 RestAPI를 호출하여 업데이트하는 방법도 있습니다. 이 경우, 이미 구현되어 있으니 노션 참조하시면 될 것 같습니다.

**Comment by SikPang** [comment]
저번에 주현누나랑 이야기했을 때 처음 친구 리스트 및 상태는 api로 받아오고, 친구가 로그아웃을 하면 그 친구의 모든 친구에게 소켓 이벤트를 날려 리스트를 재랜더링하는 방식으로 하기로 했는데 주현누나랑 이야기해 보셨나요?

**Comment by Tolerblanc** [comment]
> 다른 namespace끼리 이벤트를 주고 받을 수 있는지 실험을 안해봐서, 어떻게 동작할 지는 모르겠습니다.

이따 이 부분 실험해보고, 결과에 맞춰서 어떻게 구현할 지 논의해보겠습니다!

**Comment by OZestina** [comment]
네 어제 소켓 이벤트 날려서 바로 업데이트 하는 걸로 광식님과 얘기한 바 있어서 어제 백 미팅에서도 공유한 상태입니다
다만 해당 내용은 게임소켓에서의 내용이 다른 소켓(DM)으로 연결이 필요하고 이 부분이 구현 가능한지 확인이 필요해서 우선 구현할 수 있는 쉬운 방법인 새로고침을 공유한거고, 어떤 방향으로 진행할지는 프론트와 협의가 필요하다는 점 모두 인지하고 있습니다

**Comment by Tolerblanc** [comment]
#### 위 커밋에서 수정된 사항
- DB 유저 테이블에서 status Column 제거
- 유저의 연결 상태는 백 인메모리에 저장되어 있는 Map으로 체크 (DM 소켓, 게임 소켓 연결 여부)
- (친구 이름, 상태) 배열을 반환하는 DM 소켓 이벤트 구현

-> 차주 추가 테스트 후 이슈 닫겠습니다!

**Comment by Tolerblanc** [comment]
@ebang091 
++ 지금 로직은 RestAPI를 통해 친구 추가/제거 시 인메모리 Map을 업데이트 안해주고 있는데, 이 부분은 어떻게 할까요??
어차피 친구 리스트는 매번 DB에서 끌어오고 있어서, 인메모리 Map을 별로 활용 안하는 것 같습니다.

1. friendList Map을 없앤다.
2. 혹시나 쓰일 지 모르니, friendList 업데이트 로직을 구현한다.

**Comment by OZestina** [comment]
게임 부분은 게임socket 연결됐을 때 (status: game), 게임 socket 끊겼을 때 (dm socket 살아있는지 여부에 따라 status: online || offline) 유저의 스테이터스가 변경되었다는 이벤트를 친구들에게 보내도록 수정 및 테스트 완료했습니다 (금요일 밤 기준)

- (friendList Map이 지속적으로 업데이트되는지 확실하지 않아) DB에서 친구목록 가져와서 친구들의 dm socket에 emit 방식으로 구현
(2번으로 진행할 경우 DB -> friendList Map에서 목록 확인하는 것으로 변경하는 것은 아주 쉽습니다)

저는 어떤 방향이든 모두 좋습니다만, friendList와 blockUserList가 비슷한 목적으로 만들어졌으니 둘의 방향성이 같았으면 좋겠습니당
