### ISSUE TITLE
[Bug] chatting 테스트하면서 발생하는 버그들

### ISSUE THREAD

**Issue by ebang091** [42Seoul-LastDance/Backend#31]
- [x]  오너가 채팅방에서 나가도 방이 없어지지 않음 ⇒ back
- [x]  똑같은 이름의 채팅방 2개가 생성됨 ⇒ 아마도 back? 값은 이전방으로 남아있음

*⇒ 방 폭파 로직 수정*

- [x]  다른방에 들어가서 채팅을 치면 클라이언트 콘솔에 chatRoom is null 이 뜨는 문제
- [x]  채팅방 치고 다른 탭 갔다가 들어오면 채팅인터페이스가 남아있는 문제 ⇒ front
- [x]  채팅방이 null일 때 화면에 채팅인터페이스가 그려지는 문제 ⇒ front

*⇒ 프론트 렌더링(빈 방을 안그림) 수정*

- [x]  터진 방에 남아있으면 방 생성이 안되는 버그

*⇒ 방 터지면 튕구도록 구현 완료!*

- [x]  채팅방 유저 리스트가 갱신이 되지 않음

*⇒ 다른 컴포넌트에서 다시 리스트를 받아옴*

- [x]  비번  방에서 비번 틀렸을 때 방이 안보이는 버그

*⇒ setChatRoom() 비동기 이슈, 실패했을때도 setting을 해버리는 문제를 동기로 해결*

- [x]  방이 터지면서 나갔을때  채팅방 리스트가 업데이트 되지 않는 문제 ⇒ back… 고쳐주세요…
*⇒ explodeChatRoom 이벤트와 getChatRoomList 이벤트 발생 시점 수정으로 해결*
- [x]  mute user 부르면 터짐
- [x]  한 명 입장하는 순간 오너의 권한이 대폭 줄어들어버림. 어디선가 chatRoom정보의 권한 항목을 잘못 보내주고 있는것으로 보임 …
- [x]  getChatRoomInfo 에서 userPermission 전달하는 부분을 memberList에 (userName, Permission) 페어로 묶어서 보내는 구현으로 수정하기
*⇒(userName, Permission) 페어를 전달하는 getMemberStateList 이벤트 구현*

**Comment by Tolerblanc** [comment]
> getChatRoomInfo 에서 userPermission 전달하는 부분을 memberList에 (userName, Permission) 페어로 묶어서 보내는 구현으로 수정하기

1. 페어 배열로 보내서 프론트에서 멤버리스트 배열 들고있기
또는
2. 멤버리스트만 보내주고, 유저가 클릭 이벤트를 발생 시킬 때마다 백으로 이벤트 호출해서 어떤 드롭다운 메뉴를 보내줄 지 결정하기

**Comment by JaeJunday** [comment]
1번이나 2번으로 구현한다고 했을때, 중복되는 데이터를 여러번 호출해야하고 렌더링을 위해 다시 소켓이벤트를 호출해야 하는 문제가 있기 때문에 논의 후 chatRoomDto 자료형에서 유저리스트와 유저권한을 분리시킨 새로운 자료형(json형태의 배열)로 주고받는것으로 결정했습니다.
프론트와 주고받는 DTO를 용도에 맞게 최소단위로 쪼갰기 때문에 소켓 이벤트와 컴포넌트간의 의존성을 낮출 수 있었습니다. 이렇게 했을때 성능면에서 중복된 데이터 전송을 최소화 할 수 있다는 이점이 있습니다. 또한 필요한 데이터만 해당하는 핸들러에서 호출하기 때문에 가독성이나 디버깅 측면에서도 훨씬 효율적일 것 같습니다.

**Comment by JaeJunday** [comment]
에러 공유만 해드리고 혼선을 방지하기 위해서 백코드는 최대한 수정하지 않겠습니다.
### Socket
 - reGenerateToken called에서 토큰 시간을 5에서 10초정도로 짧게하고 여러번 리로딩했을때 확률적으로 페이지 로딩에 실패합니다. 프론트 로직부분을 체크했으나 변한부분이 없는데 백 로그 찍히는게 다른것으로보아 인증로직 어딘가에 await이 빠진걸로 보입니다.
 ### Rest api 
 - rest api에서 공격받은 시나리오나 auth에러 외에 다른 로직에서 status code 404 보내는 부분이 없는지 체크해주세요. 
front의 api handshake 로직은 2번 시도하는동안 404를 감지하면 사용자를 메인화면으로 리다이렉트 해버립니다.
 - ```/friends/request/${friendRequestName}``` 친구요청을 존재하지 않는 이름으로 보냈을때 404(not found)가 날아옵니다. + 500 error catch/ 터질 때도 있네요. 400(bad request)으로 수정 필요합니다.
 -  ```/friends/isFriend/${friendRequestName}``` 이미 친구인지 확인하는 api가 500 에러가 날아옵니다.
 ### Service
- 기본 방만들기에 실패합니다. 백로그를 봤을때 만들자마자 터지는것으로 보입니다.
- DM 저장하는 부분에서 30개이상 쌓이지 않는데 최신 N개 까지 프론트로 보내주는것으로 로직을 수정할 필요가 있습니다.

**Comment by Tolerblanc** [comment]
자세한 버그 리포트 감사합니다.
1. 확인 결과 토큰 재생성 로직쪽에는 await 빠진게 없는 것 같습니다. handleConnection시 토큰 검증하는 부분을 Async로 바꿔봐야 알 것 같아요.
2. 유저 등을 찾을 수 없을 때 404를 반환하고 있습니다. 협의 후 에러 코드 수정하겠습니다.
3. 친구 부분은 알려주신 정보를 바탕으로 추가 테스트 후 수정하겠습니다.
4. 기본 방만들기 실패는 로그를 봐야 알 것 같습니다...
5. DM 저장부분도 DB에 정상적으로 쌓이는 지 체크 후 로직 수정하겠습니다.
