### ISSUE TITLE
[fix] RestApi 구현점 이슈

### ISSUE THREAD

**Issue by JaeJunday** [42Seoul-LastDance/Backend#33]
# 버그 리포트

## 어떤 버그인가요?
유저이름에 ?를 사용했을때 찾지못하는 버그

> 버그에 대해 알려주세요
?나 @ 같은 특수기호를 사용하면 restapi요청시에 http 헤더 뒤에서 쿼리변수로 받아들여서 잘린상태로 db에 업데이트 되는 상황을 발견했습니다.
<br><br>

## 어떤 상황에서 겪으셨나요?

> 버그를 겪으신 상황을 알려주세요

<br><br>

## 참고할만한 자료가 있을까요?

> 참고자료가 있다면 첨부해주세요

<br><br>

**Comment by OZestina** [comment]
유저 input 기반으로 변경이 가능한 내용(userName)의 경우 query 말고 body에 받아오는 방식으로 수정이 필요합니다

**Comment by Tolerblanc** [comment]
위 커밋에서 사용자 입력을 API 인자로 넘겨주는 부분을 Body로 모두 수정 완료했습니다!
