### ISSUE TITLE
userName 업데이트시 소켓을 통해서 전달 받는 정보들 업데이트 필요

### ISSUE THREAD

**Issue by ebang091** [42Seoul-LastDance/Backend#34]
# 버그 리포트

## 어떤 버그인가요?
 rest api 를 이용하여 유저 네임을 변경했을 경우, 다음과 같은 이슈가 발생합니다. 
- 채팅방에 함께 속해있던 다른 유저들에게 업데이트 안됨-> 프론트에서 구버전의 username 제공으로 인해, back에서 채팅방 기능 제공 불가
- 친구 목록 업데이트 안됨-> DM을 시도하거나 친구 삭제를 시도하는 경우 back에서 404 에러 발생
- 친구 요청 목록 업데이트 안됨 -> 요청을 거절 및 수락하는 경우 back에서 404 발생

## 해결 방안
- socketEventHandler module 을 만듭니다. 
- 이 모듈은 chatSocket, DM socket 를 모두 관리 가능한 가장 상위 버전의 모듈로써, 위의 문제 상황이 일어나지 않도록 이벤트 전달을 해주는 역할을 합니다. 
- userName변경 시, 위 3가지 상황에 대해 알맞게 socket event를 전달할 예정입니다. 
- 새로운 역할의 모듈이 생김에 따라, 기능에 맞게 refactor 를 할 예정입니다!

**Comment by OZestina** [comment]
적어주신 3가지 외에도 Block user 리스트에 있는 유저 네임도 업데이트가 필요합니다
(block 해제 API가 유저 네임 기반으로 진행됩니다)

**Comment by ebang091** [comment]
friendStateList를 다시 보내주고, 친구 요청 및 차단 목록을 보여주는 rest api 요청에서는 slackId를 함께 주어서, 이후 username이 변경되더라도 slackId로 요청하도록 하여 실시간에 대응할 수 있도록 하려고 합니다.

개인적으로는 처음부터 프론트도 userId로 식별하자고 했어야 했는데, 아쉬움이 남네요. 
생길 수 있는 문제들에 대해서 고민이 부족했던 것 같아서 아쉽습니다ㅠ

**Comment by ebang091** [comment]
restapi 변경완료!
<img width="1471" alt="Screen Shot 2023-10-18 at 3 36 44 PM" src="https://github.com/42Seoul-LastDance/Backend/assets/108053947/2ae4fd16-df2f-4503-b4fa-3393b2bd9f0e">

<img width="1504" alt="Screen Shot 2023-10-18 at 3 37 05 PM" src="https://github.com/42Seoul-LastDance/Backend/assets/108053947/0d0119d6-e34a-4302-888e-107e499f627b">

**Comment by OZestina** [comment]
F->B API 요청 중 userName으로 요청받는 API는 slackID로 요청받을 수 있도록 변경 예정입니다.
- 백과 프론트에 구현된 부분 둘 다 수정할 거에요
- 노션 rest API에 수정 예정인 내용 빨간 글씨로 변경해 두었습니다 : as is(빨강) -> to be

**Comment by Tolerblanc** [comment]
위 커밋에서 문제되었던 Rest API 모두 수정 완료했습니다.
userName 변경 시 친구 리스트에서 바로 갱신 되는 것 확인했습니다.
SocketEventHandler 도입 대신, 리스트를 다시 그려야 되는 이벤트를 발생시켜서 처리했습니다
