### ISSUE TITLE
웹사이트는 `SQL Injection`으로 부터 보호되어야 합니다.

### ISSUE THREAD

**Issue by ebang091** [42Seoul-LastDance/Backend#36]
sql injection에 대한 설명

일반적인 유저라면 id = '세피로트', password='나무' 이런식으로 로그인할 것이고, 
서비스에선 database 접근 시 
`SELECT user FROM user_table WHERE id='세피로트' AND password='나무';`
다음과 같이 찾아볼 것입니다. 

그런데 sql injection은 다음과 같을 떄 일어납니다. 
짝이 맞지 않는 ''로 인해, 'false or true' == true 가 되고 OR 의 우선순위가 우선되어서 아래 구문이 실행이 되고, 모든 유저 데이터를 뽑아낼 수 있는 것입니다. 

`SELECT user FROM user_table WHERE id='admin' AND password=' ' OR '1' = '1';`

방지책
기본적으로 유저에게 받은 값을 직접 SQL로 넘기면 안 된다고 합니다. 요즘에 쓰이는 거의 모든 데이터베이스 엔진은 유저 입력이 의도치 않은 동작을 하는 걸 방지하는 escape 함수와 prepared statement를 제공한다고 하네요. prepared statement 는 변수를 문자열로 바꾸는 것이라 안전하다고 합니다. 

또한 DB에 유저별로 접근 권한과 사용 가능한 명령어를 설정하면 최악의 경우에 SQL injection에 성공하였다고 하더라도 그나마 피해를 최소화할 수 있다고 합니다. SQL injection은 데이터베이스를 알아야 가능한 공격기법이라고 하지만 스키마 구조를 몰라도 SQL injection을 사용하면 스키마 구조를 알아낼 수가 있다고 하네요. 그리고 데이터베이스를 변조하려는 게 아니라 파괴하려는 거라면 와일드카드 문자( * )를 사용해서 그냥 싹 다 지워버리는 공격이 가능하기 때문에 조심해야하는 이유가 추가됩니다. 

저희가 사용하는 database typeorm with postgresql 에서는 모두 prepared statement를 사용하였습니다. 

prepared statement란,  SQL문을 실행할 수 있는 객체이며, 기본적인 sql문과 다른 점은 캐시 사용 여부라고 합니다. 
prepared statement를 사용시에는 다음과 같은 단계로 sql문을 실행한다고 합니다. 
1. 쿼리 문장 분석
2. 컴파일
3. 실행

그리고 특징은 다음과 같습니다. 

1.  컴파일이 미리 되어있기 때문에 Statement에 비해 좋은 성능
2. 특수 문자를 자동으로 파싱해주기 때문에 SQL Injection 같은 공격을 막을 수 있음
3. '?' 부분에만 변화를 주어 쿼리문을 수행하므로 실행되는 SQL문을 파악하기 어려움
4. 쿼리 반복 수행 작업일 경우 사용하는 것이 장점.

결론: 저희는 typeorm이 제공하는  prepared statement를 사용하므로 sql injection 에 대해 방어되고 있는 것으로 간주할 수 있습니다. 

실행해볼만한 test: 

- [ ] `' OR '1' = '1`  라는 문구를 입력 값으로 넣어서 테스트 해보기.

**Comment by Tolerblanc** [comment]
테스트를 어디서 해봐야 할까요??
- [x] 닉네임을  `' OR '1' = '1` 로 바꿔본다.
- [x] DM 창에서 `' OR '1' = '1`를 입력해본다.
- [x] `' OR '1' = '1`에게 친구 요청을 해본다.
- [x] 채팅방에서 `' OR '1' = '1`를 초대해본다.

**Comment by ebang091** [comment]
queryBuilder를 사용하는 getinviteList도 확인해보겠습니다!
 - [x] invite 목록 확인하기
 - [x]  private Room invite 해보기
